# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Matthew Harazim
tagline:          'Ambient Awesomeness & Gaming Greatness'
description:      'soundDesigner// audioEngineer// producer// <a href="https://www.bearsoundstudio.com">smallBusinessOwner</a>// amateurCoder// nerd// gamer// dungeonMaster//'
url:              http://www.matthewharazim.co.uk
baseurl:          /
destination: /var/www/html/

author:
  name:           'Matt Harazim'
  url:            

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/hyde

# Plugins
plugins:
 - jekyll-paginate
 - jekyll-sitemap
 - jekyll-seo-tag
 - jekyll-feed
